name: Matlab UnitTesting on GitHub-Hosted Runner
on: [push, pull_request]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        matlab: [R2020a, R2020b, R2021a, R2021b]
        exclude:
          - os: windows-latest # available releases for win64: [R2022a R2021b R2021a]
            matlab: R2020a
          - os: windows-latest # available releases for win64: [R2022a R2021b R2021a]
            matlab: R2020b
    env:
      OS: ${{ matrix.os }}
      MATLAB: ${{ matrix.matlab }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with: 
          submodules: recursive
          #lfs: true 
      - name: download git-lfs data # avoid git-lfs traffic
        uses: actions/schmiddim-wget-unzip@v1
        with:
          url: 'https://syncandshare.lrz.de/dl/fiFCroP6zFrn64MKkiWXkDpD/20220430_tests.zip'
          destination: .
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab }}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          source-folder: .
          select-by-folder: tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./code-coverage/reports/
          env_vars: OS,MATLAB
          fail_ci_if_error: false
          files: ./code-coverage/coverage.xml, ./test-results/results.xml
          flags: cobertura, unittests
          name: matlab-helper
          path_to_write_report: ./code-coverage/codecov_report.txt
          verbose: true
